server:
   port: 8088    
   error:
      whitelabel:
         enabled: false    

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/polyclinic
    username: postgres
    password: root

  jpa:
    hibernate:
       ddl-auto: update
    show-sql: false
    database: postgresql
    generate-ddl: true